import type { InfographicSpec } from "./visualizations";

type InfographicEntry = { ar: InfographicSpec; en: InfographicSpec };

const branding = {
  primary_color: "#0B1F3A",
  secondary_color: "#0E6268",
  accent_color: "#C69214",
};

const infographics: Record<string, InfographicEntry> = {
  "divorce-procedures": {
    ar: {
      language: "ar",
      direction: "rtl",
      jurisdiction: "Jordan",
      template: "procedural-guide",
      title: "إجراءات الطلاق في الأردن",
      subtitle: "دليل شامل لمسارات الطلاق والحقوق المالية والحضانية",
      urgency: {
        enabled: true,
        label: "معلومة قانونية",
        text: "استشر محامياً متخصصاً في قانون الأحوال الشخصية قبل اتخاذ أي إجراء",
        severity: "warning",
      },
      sections: [
        {
          number: 1,
          title: "أنواع الطلاق",
          icon: "scales",
          layout: "bullets",
          items: [
            "طلاق بالتراضي: اتفاق الزوجان و ratification المحكمة (المادة 106)",
            "طلاق قضائي: طلب الزوجة لسبب مشروع كـ الإضرار أو غياب الزوج (المادة 110)",
            "تطليق بالفَرْق: مطالبة الزوجة بالطلاق أمام المحكمة مع رد المهر (المادة 113)",
          ],
        },
        {
          number: 2,
          title: "خطوات الإجراء",
          icon: "gavel",
          layout: "timeline",
          items: [
            "استشارة محامي متخصص في الأحوال الشخصية",
            "جمع المستندات: عقد الزواج والسجلات المالية",
            "تقديم الطلب أمام المحكمة المختصة",
            "حضور جلسات المحكمة والانتظار للحكم",
            "تنفيذ أحكام المحكمة وتسجيل الطلاق",
          ],
        },
        {
          number: 3,
          title: "الحقوق المالية للمرأة",
          icon: "money",
          layout: "bullets",
          items: [
            "المهر المتفق عليه في العقد النكاحي بالكامل",
            "المهر المؤجل إذا حصل الطلاق قبل الدخول",
            "نفقة العدة لمدة 3 أشهر أو حتى الولادة",
            "السكن ونفقة الأطفال وفقاً لحكم المحكمة",
          ],
        },
        {
          number: 4,
          title: "المواعيد النهائية",
          icon: "clock",
          layout: "bullets",
          items: [
            "تقديم طلب الطلاق في أي وقت طوال مدة الزواج",
            "فترة العدة: 3 أشهر قرضي أو حتى الولادة",
            "الطعن على الحكم خلال 30 يوماً من تاريخ النطق",
          ],
        },
      ],
      sources: [
        {
          label: "قانون الأحوال الشخصية الأردني رقم 36 لسنة 2017",
          reference: "المادة 106، 110، 113، 117، 118",
        },
      ],
      disclaimer:
        "هذه المعلومات للإرشاد العام فقط ولا تُعدّ استشارة قانونية. يُنصح بالرجوع إلى محامي مرخص.",
      last_reviewed: "2026-01-15",
      branding,
    },
    en: {
      language: "en",
      direction: "ltr",
      jurisdiction: "Jordan",
      template: "procedural-guide",
      title: "Divorce Procedures in Jordan",
      subtitle: "Comprehensive guide to divorce pathways, financial and custody rights",
      urgency: {
        enabled: true,
        label: "Legal Information",
        text: "Consult a lawyer specializing in personal status law before taking any action",
        severity: "warning",
      },
      sections: [
        {
          number: 1,
          title: "Types of Divorce",
          icon: "scales",
          layout: "bullets",
          items: [
            "Consensual divorce: mutual agreement ratified by the court (Article 106)",
            "Judicial divorce: wife requests divorce for legitimate cause such as harm (Article 110)",
            "Khula: wife petitions court for divorce by returning the dower (Article 113)",
          ],
        },
        {
          number: 2,
          title: "Procedure Steps",
          icon: "gavel",
          layout: "timeline",
          items: [
            "Consult a lawyer specializing in personal status law",
            "Gather documents: marriage contract and financial records",
            "File the petition before the competent court",
            "Attend court hearings and receive the judgment",
            "Execute court orders and register the divorce",
          ],
        },
        {
          number: 3,
          title: "Financial Rights",
          icon: "money",
          layout: "bullets",
          items: [
            "Full dower agreed in the marriage contract",
            "Deferred dower if divorce occurs before consummation",
            "Iddah maintenance for 3 months or until delivery",
            "Housing and child support per court ruling",
          ],
        },
        {
          number: 4,
          title: "Key Deadlines",
          icon: "clock",
          layout: "bullets",
          items: [
            "Divorce petition may be filed at any time during marriage",
            "Iddah period: 3 months or until delivery if pregnant",
            "Appeal period: 30 days from the date of issuance",
          ],
        },
      ],
      sources: [
        {
          label: "Jordanian Personal Status Law No. 36 of 2017",
          reference: "Articles 106, 110, 113, 117, 118",
        },
      ],
      disclaimer:
        "This information is for general guidance only and does not constitute legal advice. You are advised to consult a licensed lawyer.",
      last_reviewed: "2026-01-15",
      branding,
    },
  },
  "employee-termination-jordan": {
    ar: {
      language: "ar",
      direction: "rtl",
      jurisdiction: "Jordan",
      template: "legal-summary",
      title: "إنهاء عقد العمل في الأردن",
      subtitle: "حقوق الموظف عند الفصل التعسفي وقانون العمل رقم 8 لسنة 1996",
      urgency: {
        enabled: true,
        label: "تنبيه عاجل",
        text: "تصرف فوراً بعد تلقي إنذار الفصل - لا تؤجل المطالبة أكثر من سنة",
        severity: "urgent",
      },
      sections: [
        {
          number: 1,
          title: "حقوقك القانونية",
          icon: "shield",
          layout: "bullets",
          items: [
            "إنذار كتابي مسبق: 3 أشهر (5 سنوات فأكثر) أو شهر ونصف (أقل)",
            "تعويض عن الفصل التعسفي وفقاً للمادة 29",
            "مكافأة نهاية الخدمة: نصف شهر عن كل سنة (أول 5 سنوات) وشهر كامل بعدها",
            "يُمنع الفصل بسبب نشاط النقابة أو العرق أو الدين أو الجنس",
          ],
        },
        {
          number: 2,
          title: "الإجراءات القانونية",
          icon: "gavel",
          layout: "timeline",
          items: [
            "راجع عقد العمل وتأكد من بنود الفصل",
            "أرسل مطالبة رسمية لصاحب العمل",
            "قدّم شكوى لوزارة العمل أو دعوى أمام المحكمة الابتدائية",
            "احضر الجلسة مع جميع الأدلة والشهود",
            "نفّذ الحكم عبر مكتب التنفيذ",
          ],
        },
        {
          number: 3,
          title: "المستندات المطلوبة",
          icon: "documents",
          layout: "checklist",
          items: [
            "عقد العمل الأصلي",
            "إنذار الفصل الكتابي",
            "كشوف الرواتب ومستندات التأمينات",
            "المراسلات بين الطرفين",
            "شهادة خبرة العمل",
          ],
        },
        {
          number: 4,
          title: "المواعيد النهائية",
          icon: "calendar",
          layout: "bullets",
          items: [
            "تقديم الدعوى خلال سنة من تاريخ الفصل",
            "الطعن على الحكم خلال 30 يوماً",
          ],
        },
      ],
      sources: [
        {
          label: "قانون العمل الأردني رقم 8 لسنة 1996",
          reference: "المادة 27، 28، 29، 30، 104",
        },
      ],
      disclaimer:
        "هذه المعلومات للإرشاد العام فقط ولا تُعدّ استشارة قانونية. يُنصح بالرجوع إلى محامي مرخص.",
      last_reviewed: "2026-01-15",
      branding,
    },
    en: {
      language: "en",
      direction: "ltr",
      jurisdiction: "Jordan",
      template: "legal-summary",
      title: "Wrongful Termination in Jordan",
      subtitle: "Employee rights upon dismissal under Labor Law No. 8 of 1996",
      urgency: {
        enabled: true,
        label: "Urgent Notice",
        text: "Act immediately upon receiving a termination notice - do not delay more than one year",
        severity: "urgent",
      },
      sections: [
        {
          number: 1,
          title: "Your Legal Rights",
          icon: "shield",
          layout: "bullets",
          items: [
            "Advance written notice: 3 months (5+ years) or 1.5 months (less than 5 years)",
            "Compensation for arbitrary dismissal under Article 29",
            "End-of-service gratuity: half month per year (first 5 years) then full month",
            "Dismissal prohibited based on union activity, ethnicity, religion, or gender",
          ],
        },
        {
          number: 2,
          title: "Legal Procedure",
          icon: "gavel",
          layout: "timeline",
          items: [
            "Review employment contract and termination provisions",
            "Send a formal demand to the employer",
            "File a complaint with the Ministry of Labor or lawsuit at the Magistrates Court",
            "Attend hearing with all evidence and witnesses",
            "Execute the judgment through the Execution Office",
          ],
        },
        {
          number: 3,
          title: "Required Documents",
          icon: "documents",
          layout: "checklist",
          items: [
            "Original employment contract",
            "Written termination notice",
            "Salary statements and social security documentation",
            "Correspondence between the parties",
            "Work experience certificate",
          ],
        },
        {
          number: 4,
          title: "Key Deadlines",
          icon: "calendar",
          layout: "bullets",
          items: [
            "File the claim within one year of dismissal",
            "Appeal period: 30 days from the judgment",
          ],
        },
      ],
      sources: [
        {
          label: "Jordanian Labor Law No. 8 of 1996",
          reference: "Articles 27, 28, 29, 30, 104",
        },
      ],
      disclaimer:
        "This information is for general guidance only and does not constitute legal advice. You are advised to consult a licensed lawyer.",
      last_reviewed: "2026-01-15",
      branding,
    },
  },
  "traffic-accident-liability": {
    ar: {
      language: "ar",
      direction: "rtl",
      jurisdiction: "Jordan",
      template: "procedural-guide",
      title: "تحديد المسؤولية في حوادث المرور",
      subtitle: "دليل إجرائي لتوثيق الحادث والمطالبة بالتعويض",
      urgency: {
        enabled: true,
        label: "خطوة أولى",
        text: "أبلغ الشرطة فوراً وقم بتوثيق الحادث من جميع الزوايا",
        severity: "urgent",
      },
      sections: [
        {
          number: 1,
          title: "الخطوات الفورية بعد الحادث",
          icon: "warning",
          layout: "timeline",
          items: [
            "أبلغ الشرطة فوراً على الرقم 911",
            "قم بتوثيق الحادث بالصور من جميع الزوايا",
            "اجمع شهادات شهود العيان",
            "احصل على نسخة من تقرير الشرطة",
          ],
        },
        {
          number: 2,
          title: "المسؤولية القانونية",
          icon: "scales",
          layout: "bullets",
          items: [
            "تُحدد المسؤولية وفقاً لقانون المرور رقم 49 لسنة 2000 والقانون المدني",
            "تقرير الشرطة هو الدليل الأساسي للمسؤولية الأولية",
            "يمكن المحكمة تحديد نسبة المسؤولية وفقاً لنسبة الإخلال من كل طرف",
            "يمكن الطعن على تقرير الشرطة أمام المحكمة",
          ],
        },
        {
          number: 3,
          title: "أنواع التأمين",
          icon: "shield",
          layout: "two_columns",
          columns: [
            {
              title: "التأمين الإلزامي",
              text: "يغطي الحد الأدنى من المسؤولية تجاه الطرف الثالث فقط",
              icon: "documents",
            },
            {
              title: "التأمين الشامل",
              text: "يغطي أضرار السيارة والطرف الثالث والmassage الشخصية",
              icon: "shield",
            },
          ],
          items: [],
        },
        {
          number: 4,
          title: "المطالبة بالتعويض",
          icon: "money",
          layout: "bullets",
          items: [
            "تواصل مع شركة التأمين لتقديم المطالبة خلال 30 يوماً",
            "أرفق تقرير الشرطة والصور والشهادات",
            "إذا لزم الأمر، قدم دعوى أمام المحكمة لتحدي المسؤولية",
            "تقديم الدعوى خلال سنة من تاريخ الحادث",
          ],
        },
      ],
      sources: [
        {
          label: "قانون المرور الأردني رقم 49 لسنة 2000",
          reference: "المادة 48، 49",
        },
        {
          label: "القانون المدني الأردني رقم 36 لسنة 1976",
          reference: "المادة 256 المسؤولية التقصيرية",
        },
      ],
      disclaimer:
        "هذه المعلومات للإرشاد العام فقط ولا تُعدّ استشارة قانونية. يُنصح بالرجوع إلى محامي مرخص.",
      last_reviewed: "2026-01-15",
      branding,
    },
    en: {
      language: "en",
      direction: "ltr",
      jurisdiction: "Jordan",
      template: "procedural-guide",
      title: "Traffic Accident Liability",
      subtitle: "Procedural guide for documenting accidents and claiming compensation",
      urgency: {
        enabled: true,
        label: "First Step",
        text: "Report to police immediately and document the accident from all angles",
        severity: "urgent",
      },
      sections: [
        {
          number: 1,
          title: "Immediate Steps After Accident",
          icon: "warning",
          layout: "timeline",
          items: [
            "Report to police immediately at 911",
            "Document the accident with photos from all angles",
            "Collect witness statements",
            "Obtain a copy of the police report",
          ],
        },
        {
          number: 2,
          title: "Legal Liability",
          icon: "scales",
          layout: "bullets",
          items: [
            "Liability determined under Traffic Law No. 49/2000 and Civil Code",
            "Police report is primary evidence for initial liability",
            "Court may apportion liability based on each party's degree of fault",
            "Police report may be challenged in court",
          ],
        },
        {
          number: 3,
          title: "Insurance Types",
          icon: "shield",
          layout: "two_columns",
          columns: [
            {
              title: "Mandatory Insurance",
              text: "Covers minimum third-party liability only",
              icon: "documents",
            },
            {
              title: "Comprehensive Insurance",
              text: "Covers vehicle damage, third-party liability, and personal injury",
              icon: "shield",
            },
          ],
          items: [],
        },
        {
          number: 4,
          title: "Claiming Compensation",
          icon: "money",
          layout: "bullets",
          items: [
            "Contact the insurance company to file a claim within 30 days",
            "Attach police report, photos, and witness statements",
            "If necessary, file a lawsuit to challenge liability",
            "File the lawsuit within one year of the accident",
          ],
        },
      ],
      sources: [
        {
          label: "Jordanian Traffic Law No. 49 of 2000",
          reference: "Articles 48, 49",
        },
        {
          label: "Jordanian Civil Code No. 36 of 1976",
          reference: "Article 256 - Tortious Liability",
        },
      ],
      disclaimer:
        "This information is for general guidance only and does not constitute legal advice. You are advised to consult a licensed lawyer.",
      last_reviewed: "2026-01-15",
      branding,
    },
  },
  "security-deposit-refund": {
    ar: {
      language: "ar",
      direction: "rtl",
      jurisdiction: "Jordan",
      template: "procedural-guide",
      title: "استرداد تأمين الإيجار",
      subtitle: "دليل إجرائي لاسترداد وديعة التأمين من المؤجر",
      urgency: {
        enabled: true,
        label: "معلومة مهمة",
        text: "لا تؤجل المطالبة أكثر من 30 يوماً بعد انتهاء العقد",
        severity: "warning",
      },
      sections: [
        {
          number: 1,
          title: "حقوقك كمستأجر",
          icon: "shield",
          layout: "bullets",
          items: [
            "وديعة التأمين (رهن أمانة) يلزم المؤجر بإعادتها بعد التسليم",
            "لا يُخصم التأمين إلا للضرر الفعلي أو الإيجار غير المدفوع",
            "تسليم المفتاح دون اعتراض يُعدّ قبولاً لحالة الإيجار",
            "النزاع يُنظر أمام المحكمة الابتدائية كنزاع مدني",
          ],
        },
        {
          number: 2,
          title: "خطوات الاسترداد",
          icon: "gavel",
          layout: "timeline",
          items: [
            "راجع عقد الإيجار وتأكد من شروط التأمين",
            "وثّق حالة الوحدة بالصور والفيديو عند التسليم",
            "أرسل مطالبة رسمية للمؤجر عبر بريد مسجل",
            "إذا لم يستجب، قدم دعوى أمام المحكمة الابتدائية",
            "احضر الجلسة مع جميع الأدلة",
            "نفّذ الحكم عبر مكتب التنفيذ",
          ],
        },
        {
          number: 3,
          title: "المستندات المطلوبة",
          icon: "documents",
          layout: "checklist",
          items: [
            "عقد الإيجار الأصلي",
            "إيصال دفع وديعة التأمين",
            "صور وفيديو حالة الشقة عند التسليم",
            "مطالبة رسمية خطاب مسجل أو من المحامي",
            "محضر التسليم أو إثبات تسليم المفتاح",
          ],
        },
        {
          number: 4,
          title: "المواعيد النهائية",
          icon: "calendar",
          layout: "bullets",
          items: [
            "15 يوماً للمؤجر للرد على المطالبة الرسمية",
            "تقديم الدعوى خلال 30 يوماً من انتهاء العقد",
            "التقادم العام 15 سنة للدعاوى المدنية",
          ],
        },
      ],
      sources: [
        {
          label: "القانون المدني الأردني رقم 36 لسنة 1976",
          reference: "المادة 246-265، 1072-1077",
        },
        {
          label: "قانون أصول المحاكمات المدنية رقم 24 لسنة 1988",
          reference: "المادة 39 اختصاص المحكمة",
        },
        {
          label: "قانون التنفيذ رقم 25 لسنة 2017",
          reference: "المادة 4-5",
        },
      ],
      disclaimer:
        "هذه المعلومات للإرشاد العام فقط ولا تُعدّ استشارة قانونية. يُنصح بالرجوع إلى محامي مرخص.",
      last_reviewed: "2026-01-15",
      branding,
    },
    en: {
      language: "en",
      direction: "ltr",
      jurisdiction: "Jordan",
      template: "procedural-guide",
      title: "Security Deposit Refund",
      subtitle: "Procedural guide for recovering your deposit from the landlord",
      urgency: {
        enabled: true,
        label: "Important",
        text: "Do not delay the demand for more than 30 days after lease termination",
        severity: "warning",
      },
      sections: [
        {
          number: 1,
          title: "Your Rights as Tenant",
          icon: "shield",
          layout: "bullets",
          items: [
            "The deposit (wadiah amanah) must be returned by the landlord after handover",
            "Deductions allowed only for actual damage or unpaid rent",
            "Handing over keys without objection constitutes acceptance",
            "Disputes heard at the Magistrates Court as civil cases",
          ],
        },
        {
          number: 2,
          title: "Recovery Steps",
          icon: "gavel",
          layout: "timeline",
          items: [
            "Review the lease and verify deposit refund provisions",
            "Document unit condition with photos and video at handover",
            "Send a formal demand to the landlord via registered mail",
            "If no response, file a claim at the Magistrates Court",
            "Attend the hearing with all evidence",
            "Execute the judgment through the Execution Office",
          ],
        },
        {
          number: 3,
          title: "Required Documents",
          icon: "documents",
          layout: "checklist",
          items: [
            "Original lease agreement",
            "Deposit payment receipt",
            "Photos and video of unit condition at handover",
            "Formal demand letter registered mail or lawyer notice",
            "Handover report or proof of key delivery",
          ],
        },
        {
          number: 4,
          title: "Key Deadlines",
          icon: "calendar",
          layout: "bullets",
          items: [
            "15-day period for landlord to respond to formal demand",
            "File claim within 30 days of lease termination",
            "General prescription period: 15 years for civil claims",
          ],
        },
      ],
      sources: [
        {
          label: "Jordanian Civil Code No. 36 of 1976",
          reference: "Articles 246-265, 1072-1077",
        },
        {
          label: "Civil Procedure Law No. 24 of 1988",
          reference: "Article 39 - Court Jurisdiction",
        },
        {
          label: "Execution Law No. 25 of 2017",
          reference: "Articles 4-5",
        },
      ],
      disclaimer:
        "This information is for general guidance only and does not constitute legal advice. You are advised to consult a licensed lawyer.",
      last_reviewed: "2026-01-15",
      branding,
    },
  },
};

export function getInfographic(slug: string, lang: "ar" | "en"): InfographicSpec | undefined {
  const entry = infographics[slug];
  if (!entry) return undefined;
  return entry[lang];
}

export function getAvailableInfographicSlugs(): string[] {
  return Object.keys(infographics);
}

export { infographics };

export interface InfographicGalleryEntry {
  id: string;
  slug: string;
  filename: string;
  category: string;
  titleAr: string;
  titleEn: string;
  descriptionAr: string;
  descriptionEn: string;
  language: "ar" | "en" | "both";
  template: "legal-summary" | "procedural-guide" | "document-checklist" | "deadline-warning";
  lastReviewed: string;
}

export const infographicGallery: InfographicGalleryEntry[] = [
  // ── Insurance ──────────────────────────────────────────────
  {
    id: "claim-rejection-objection",
    slug: "insurance-claim-rejection",
    filename: "insurance-claim-rejection-objection-infographic-final.png",
    category: "Insurance",
    titleAr: "اعتراض رفض مطالبة تأمين",
    titleEn: "Insurance Claim Rejection Objection",
    descriptionAr: "دليل إجرائي لاعتراض قرار رفض مطالبة التأمين واستئناف المطالبة",
    descriptionEn: "Procedural guide to objecting an insurance claim rejection and reinstating the claim",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "complaint-central-bank",
    slug: "insurance-complaint-central-bank",
    filename: "insurance-complaint-central-bank-infographic-final.png",
    category: "Insurance",
    titleAr: "شكوى التأمين للبنك المركزي",
    titleEn: "Insurance Complaint to Central Bank",
    descriptionAr: "كيفية تقديم شكوى رسمية ضد شركة التأمين لدى البنك المركزي الأردني",
    descriptionEn: "How to file a formal complaint against an insurance company with the Central Bank of Jordan",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "limitation-period",
    slug: "insurance-limitation-period",
    filename: "insurance-limitation-period-infographic-final.png",
    category: "Insurance",
    titleAr: "فترة التقادم في التأمين",
    titleEn: "Insurance Limitation Period",
    descriptionAr: "المواعيد النهائية والتقادم القانوني لمطالبات التأمين في الأردن",
    descriptionEn: "Statutory deadlines and limitation periods for insurance claims in Jordan",
    language: "ar",
    template: "deadline-warning",
    lastReviewed: "2026-08-18",
  },
  {
    id: "comprehensive-vs-compulsory",
    slug: "insurance-comprehensive-vs-compulsory",
    filename: "jordan-comprehensive-vs-compulsory-insurance-infographic-branded.png",
    category: "Insurance",
    titleAr: "التأمين الشامل مقابل الإلزامي",
    titleEn: "Comprehensive vs Compulsory Insurance",
    descriptionAr: "مقارنة بين التأمين الإلزامي والشامل ونطاق التغطية لكل منهما",
    descriptionEn: "Comparison between compulsory and comprehensive insurance and their coverage scope",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "traffic-claim-limitation",
    slug: "insurance-traffic-claim",
    filename: "jordan-insurance-traffic-claim-limitation-infographic-branded.png",
    category: "Insurance",
    titleAr: "مطالبة تأمين المرور",
    titleEn: "Traffic Insurance Claim",
    descriptionAr: "المواعيد النهائية وإجراءات المطالبة بتأمين الحوادث المرورية",
    descriptionEn: "Deadlines and procedures for filing traffic accident insurance claims",
    language: "ar",
    template: "deadline-warning",
    lastReviewed: "2026-08-18",
  },

  // ── Cybercrime ─────────────────────────────────────────────
  {
    id: "cybercrime-overview-ar",
    slug: "cybercrime-overview",
    filename: "jordan_cybercrime_infographic_ar.png",
    category: "Cybercrime",
    titleAr: "الجرائم الإلكترونية في الأردن",
    titleEn: "Cybercrime in Jordan",
    descriptionAr: "نظرة عامة على الجرائم الإلكترونية وتشريعاتها في الأردن",
    descriptionEn: "Overview of cybercrime types and their legislation in Jordan",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "reporting-ar",
    slug: "cybercrime-reporting",
    filename: "jordan_cybercrime_reporting_infographic_ar_corrected_white.png",
    category: "Cybercrime",
    titleAr: "كيفية الإبلاغ عن جرائم الإنترنت",
    titleEn: "How to Report Cybercrime",
    descriptionAr: "خطوات الإبلاغ عن الجرائم الإلكترونية لدى الجهات المختصة",
    descriptionEn: "Steps to report cybercrime to the relevant authorities",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "reporting-ar-v2",
    slug: "cybercrime-reporting-v2",
    filename: "jordan_cybercrime_reporting_infographic_ar_v2.png",
    category: "Cybercrime",
    titleAr: "دليل الإبلاغ عن الجرائم الإلكترونية",
    titleEn: "Cybercrime Reporting Guide",
    descriptionAr: "دليل شامل محدّث للإبلاغ عن الجرائم الإلكترونية في الأردن",
    descriptionEn: "Updated comprehensive guide for reporting cybercrime in Jordan",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "reporting-en",
    slug: "cybercrime-reporting-en",
    filename: "jordan_cybercrime_reporting_infographic_en.png",
    category: "Cybercrime",
    titleAr: "الإبلاغ عن الجرائم الإلكترونية بالإنجليزية",
    titleEn: "Cybercrime Reporting (English)",
    descriptionAr: "دليل الإبلاغ عن الجرائم الإلكترونية باللغة الإنجليزية",
    descriptionEn: "English-language guide to reporting cybercrime in Jordan",
    language: "en",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },

  // ── Rent & Real Estate ─────────────────────────────────────
  {
    id: "deposit-notice-ar",
    slug: "security-deposit-refund",
    filename: "jordan_rent_deposit_notice_infographic_ar.png",
    category: "Rent & Real Estate",
    titleAr: "إشعار تأمين الإيجار",
    titleEn: "Rent Deposit Notice",
    descriptionAr: "نموذج إشعار استرداد وديعة التأمين ومتطلباته القانونية",
    descriptionEn: "Template and legal requirements for a rent deposit refund notice",
    language: "ar",
    template: "document-checklist",
    lastReviewed: "2026-08-18",
  },
  {
    id: "nonpayment-defense-ar",
    slug: "rent-nonpayment",
    filename: "jordan_rent_nonpayment_defense_infographic_ar.png",
    category: "Rent & Real Estate",
    titleAr: "الدفاع عن عدم دفع الإيجار",
    titleEn: "Rent Nonpayment Defense",
    descriptionAr: "الدفاع القانوني في حالة مطالبة المؤجر بعدم دفع الإيجار",
    descriptionEn: "Legal defenses when a landlord claims rent nonpayment",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "force-majeure-ar",
    slug: "rent-force-majeure",
    filename: "jordan_rent_payment_force_majeure_infographic_ar.png",
    category: "Rent & Real Estate",
    titleAr: "القوة القاهرة في الإيجار",
    titleEn: "Force Majeure in Rent",
    descriptionAr: "تأثير القوة القاهرة على عقود الإيجار والحقوق المترتبة عليها",
    descriptionEn: "Impact of force majeure on lease contracts and resulting rights",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "contract-issues-ar",
    slug: "rent-contract-issues",
    filename: "jordan_rental_contract_issues_infographic_ar.png",
    category: "Rent & Real Estate",
    titleAr: "مشاكل عقد الإيجار",
    titleEn: "Rental Contract Issues",
    descriptionAr: "المشكلات الشائعة في عقود الإيجار وكيفية التعامل معها قانونياً",
    descriptionEn: "Common rental contract issues and how to address them legally",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "dates-notices-ar",
    slug: "rent-dates-notices",
    filename: "jordan_rental_dates_notices_infographic_ar.png",
    category: "Rent & Real Estate",
    titleAr: "التواريخ والإشعارات الإيجارية",
    titleEn: "Rental Dates and Notices",
    descriptionAr: "المواعيد النهائية والإشعارات المطلوبة قانونياً في عقود الإيجار",
    descriptionEn: "Deadlines and legally required notices in lease agreements",
    language: "ar",
    template: "deadline-warning",
    lastReviewed: "2026-08-18",
  },
  {
    id: "disputes-ar",
    slug: "rent-disputes",
    filename: "jordan_rental_disputes_infographic_ar.png",
    category: "Rent & Real Estate",
    titleAr: "نزاعات الإيجار",
    titleEn: "Rental Disputes",
    descriptionAr: "طرق حل نزاعات الإيجار والإجراءات القانونية المتاحة",
    descriptionEn: "Methods for resolving rental disputes and available legal procedures",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "eviction-procedure-ar",
    slug: "eviction-process",
    filename: "jordan_rental_eviction_procedure_infographic_ar.png",
    category: "Rent & Real Estate",
    titleAr: "إجراءات الإخلاء",
    titleEn: "Eviction Procedure",
    descriptionAr: "الخطوات القانونية الكاملة لإجراء الإخلاء في الأردن",
    descriptionEn: "Complete legal steps for the eviction process in Jordan",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "real-estate-overview-ar",
    slug: "real-estate-overview",
    filename: "jordan_rentals_real_estate_infographic_ar.png",
    category: "Rent & Real Estate",
    titleAr: "نظرة عامة على الإيجار والعقارات",
    titleEn: "Rent and Real Estate Overview",
    descriptionAr: "نظرة شاملة على قوانين الإيجار والعقارات في الأردن",
    descriptionEn: "Comprehensive overview of rental and real estate laws in Jordan",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "urgent-eviction-ar",
    slug: "urgent-eviction",
    filename: "jordan_urgent_eviction_infographic_ar.png",
    category: "Rent & Real Estate",
    titleAr: "الإخلاء العاجل",
    titleEn: "Urgent Eviction",
    descriptionAr: "إجراءات الإخلاء العاجل ومتطلباته القانونية في حالات الطوارئ",
    descriptionEn: "Urgent eviction procedures and legal requirements in emergency cases",
    language: "ar",
    template: "deadline-warning",
    lastReviewed: "2026-08-18",
  },

  // ── Checks & Banking ───────────────────────────────────────
  {
    id: "check-deadlines",
    slug: "check-deadlines",
    filename: "jordan-check-deadlines-infographic-branded.png",
    category: "Checks & Banking",
    titleAr: "المواعيد القانونية للشيكات",
    titleEn: "Check Deadlines",
    descriptionAr: "المواعيد النهائية القانونية لصرف وتقديم الشيكات في الأردن",
    descriptionEn: "Statutory deadlines for presenting and cashing checks in Jordan",
    language: "ar",
    template: "deadline-warning",
    lastReviewed: "2026-08-18",
  },
  {
    id: "deferred-check-branded",
    slug: "deferred-check",
    filename: "jordan-deferred-check-infographic-branded.png",
    category: "Checks & Banking",
    titleAr: "الشيك المؤجل",
    titleEn: "Deferred Check",
    descriptionAr: "الحقوق القانونية والإجراءات المتعلقة بالشيكات المؤجلة",
    descriptionEn: "Legal rights and procedures related to deferred checks",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "deferred-check-tajawal",
    slug: "deferred-check-tajawal",
    filename: "jordan-deferred-check-infographic-tajawal-white.png",
    category: "Checks & Banking",
    titleAr: "الشيك المؤجل - تجول",
    titleEn: "Deferred Check - Tajawal",
    descriptionAr: "الإجراءات القانونية للشيكات المؤجلة عبر تطبيق تجول",
    descriptionEn: "Legal procedures for deferred checks through Tajawal app",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "deferred-check-white",
    slug: "deferred-check-white",
    filename: "jordan-deferred-check-infographic-white-branded.png",
    category: "Checks & Banking",
    titleAr: "الشيك المؤجل - نسخة بيضاء",
    titleEn: "Deferred Check - White",
    descriptionAr: "إصدار الشيك المؤجل على ورقة بيضاء و hậu quảه القانونية",
    descriptionEn: "Issuing a deferred check on blank paper and its legal consequences",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "old-new-checks",
    slug: "old-new-checks",
    filename: "jordan-old-new-checks-infographic-branded.png",
    category: "Checks & Banking",
    titleAr: "الشيكات القديمة والجديدة",
    titleEn: "Old and New Checks",
    descriptionAr: "مقارنة بين الشيكات القديمة والجديدة والتحديثات القانونية",
    descriptionEn: "Comparison between old and new check formats and legal updates",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "returned-checks",
    slug: "returned-checks",
    filename: "jordan-returned-checks-infographic.png",
    category: "Checks & Banking",
    titleAr: "الشيكات المرتجعة",
    titleEn: "Returned Checks",
    descriptionAr: "الإجراءات القانونية عند إرجاع الشيك من البنك والخيارات المتاحة",
    descriptionEn: "Legal procedures when a check is returned by the bank and available options",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },

  // ── Family Law ─────────────────────────────────────────────
  {
    id: "child-custody-support",
    slug: "child-custody",
    filename: "jordan-child-custody-support-infographic-branded.png",
    category: "Family Law",
    titleAr: "حضانة الأطفال ونفقتهم",
    titleEn: "Child Custody and Support",
    descriptionAr: "حقوق الحضانة والنفقة للأطفال وفقاً لقانون الأحوال الشخصية الأردني",
    descriptionEn: "Child custody rights and support under Jordanian Personal Status Law",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "cross-border-guide",
    slug: "cross-border-family",
    filename: "jordan-cross-border-family-law-guide-infographic-branded.png",
    category: "Family Law",
    titleAr: "الدليل العابر للحدود في الأحوال الشخصية",
    titleEn: "Cross-Border Family Law Guide",
    descriptionAr: "الاعتبارات القانونية عبر الحدود في قضايا الأحوال الشخصية",
    descriptionEn: "Cross-border legal considerations in family status matters",
    language: "both",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "divorce-separation-process",
    slug: "divorce-procedures",
    filename: "jordan-divorce-separation-process-infographic-branded.png",
    category: "Family Law",
    titleAr: "إجراءات الطلاق والتفريق",
    titleEn: "Divorce and Separation Process",
    descriptionAr: "دليل شامل لإجراءات الطلاق والتفريق القضائي في الأردن",
    descriptionEn: "Comprehensive guide to divorce and judicial separation procedures in Jordan",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "irrevocable-divorce",
    slug: "irrevocable-divorce",
    filename: "jordan-irrevocable-divorce-infographic-final.png",
    category: "Family Law",
    titleAr: "الطلاق البائن",
    titleEn: "Irrevocable Divorce",
    descriptionAr: "أحكام الطلاق البائن وآثاره القانونية على الحقوق المالية والحضانية",
    descriptionEn: "Rulings on irrevocable divorce and its legal impact on financial and custody rights",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "judicial-separation-grounds",
    slug: "judicial-separation-grounds",
    filename: "jordan-judicial-separation-grounds-infographic-branded.png",
    category: "Family Law",
    titleAr: "أسباب التفريق القضائي",
    titleEn: "Judicial Separation Grounds",
    descriptionAr: "الأسباب القانونية المعتبرة للتفريق القضائي في المحكمة",
    descriptionEn: "Recognized legal grounds for judicial separation in court",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "judicial-separation-without-consent",
    slug: "judicial-separation-without-consent",
    filename: "jordan-judicial-separation-without-consent-infographic-branded.png",
    category: "Family Law",
    titleAr: "التفريق دون موافقة",
    titleEn: "Judicial Separation Without Consent",
    descriptionAr: "إجراءات طلب التفريق القضائي دون موافقة الطرف الآخر",
    descriptionEn: "Procedures for seeking judicial separation without the other party's consent",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "maternal-custody-loss-final",
    slug: "maternal-custody-loss",
    filename: "jordan-maternal-custody-loss-infographic-branded-final.png",
    category: "Family Law",
    titleAr: "فقدان حضانة الأم",
    titleEn: "Maternal Custody Loss",
    descriptionAr: "الأسباب القانونية التي تؤدي لفقدان الأم لحق حضانة أطفالها",
    descriptionEn: "Legal causes that lead to a mother losing child custody rights",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "maternal-custody-loss",
    slug: "maternal-custody-loss-alt",
    filename: "jordan-maternal-custody-loss-infographic-branded.png",
    category: "Family Law",
    titleAr: "سقوط حضانة الأم",
    titleEn: "Loss of Maternal Custody",
    descriptionAr: "حالات سقوط حضانة الأم وفقاً لقانون الأحوال الشخصية",
    descriptionEn: "Cases of loss of maternal custody under Personal Status Law",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "post-divorce-rights-final",
    slug: "post-divorce-rights",
    filename: "jordan-post-divorce-rights-infographic-final.png",
    category: "Family Law",
    titleAr: "الحقوق بعد الطلاق",
    titleEn: "Post-Divorce Rights",
    descriptionAr: "الحقوق المالية والقانونية للمرأة بعد الطلاق في الأردن",
    descriptionEn: "Financial and legal rights of women after divorce in Jordan",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "post-divorce-rights-overview",
    slug: "post-divorce-rights-overview",
    filename: "jordan-post-divorce-rights-overview-infographic-branded.png",
    category: "Family Law",
    titleAr: "نظرة عامة على حقوق ما بعد الطلاق",
    titleEn: "Post-Divorce Rights Overview",
    descriptionAr: "نظرة شاملة على جميع الحقوق المترتبة بعد الطلاق",
    descriptionEn: "Comprehensive overview of all rights arising after divorce",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "idda-maintenance-loss",
    slug: "idda-maintenance",
    filename: "jordan-idda-maintenance-loss-infographic-branded.png",
    category: "Family Law",
    titleAr: "العدة والنفقة وفقدانها",
    titleEn: "Idda, Maintenance and Loss",
    descriptionAr: "أحكام العدة ونفقتها وحالات فقدان الحق في النفقة",
    descriptionEn: "Rulings on iddah and its maintenance, and cases of losing the right to support",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },

  // ── Labor Law ──────────────────────────────────────────────
  {
    id: "labor-disputes",
    slug: "wrongful-termination",
    filename: "jordan-labor-disputes-infographic-branded.png",
    category: "Labor Law",
    titleAr: "نزاعات العمل في الأردن",
    titleEn: "Labor Disputes in Jordan",
    descriptionAr: "دليل إجرائي لحل نزاعات العمل والفصل التعسفي في الأردن",
    descriptionEn: "Procedural guide to resolving labor disputes and wrongful termination in Jordan",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "limitation-rules",
    slug: "labor-limitation",
    filename: "jordan-labor-limitation-rules-infographic-branded.png",
    category: "Labor Law",
    titleAr: "قواعد التقادم في العمل",
    titleEn: "Labor Limitation Rules",
    descriptionAr: "مواعيد التقادم القانوني للمطالبات العمالية في الأردن",
    descriptionEn: "Statutory limitation periods for labor claims in Jordan",
    language: "ar",
    template: "deadline-warning",
    lastReviewed: "2026-08-18",
  },
  {
    id: "rights-guide",
    slug: "labor-rights",
    filename: "jordan-labor-rights-guide-infographic-branded.png",
    category: "Labor Law",
    titleAr: "دليل حقوق العمال",
    titleEn: "Worker Rights Guide",
    descriptionAr: "دليل شامل لحقوق العمال وفقاً لقانون العمل الأردني",
    descriptionEn: "Comprehensive guide to worker rights under Jordanian Labor Law",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "probation-period",
    slug: "probation-period",
    filename: "jordan-probation-period-infographic-branded.png",
    category: "Labor Law",
    titleAr: "فترة التجربة",
    titleEn: "Probation Period",
    descriptionAr: "أحكام فترة التجربة في عقد العمل وحقوق الطرفين",
    descriptionEn: "Rules governing the probation period in employment contracts and rights of both parties",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "probation-termination",
    slug: "probation-termination",
    filename: "jordan-probation-termination-rights-infographic-branded.png",
    category: "Labor Law",
    titleAr: "إنهاء فترة التجربة",
    titleEn: "Probation Termination",
    descriptionAr: "إجراءات إنهاء فترة التجربة وحقوق العامل عند الإنهاء",
    descriptionEn: "Procedures for ending the probation period and worker rights upon termination",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "probation-worker-rights",
    slug: "probation-rights",
    filename: "jordan-probation-worker-rights-infographic-branded.png",
    category: "Labor Law",
    titleAr: "حقوق العامل أثناء التجربة",
    titleEn: "Worker Rights During Probation",
    descriptionAr: "الحقوق المكفولة للعامل أثناء فترة التجربة في العقد",
    descriptionEn: "Rights guaranteed to workers during the probation period of the contract",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "unfair-dismissal",
    slug: "unfair-dismissal",
    filename: "jordan-unfair-dismissal-infographic-branded.png",
    category: "Labor Law",
    titleAr: "الفصل التعسفي",
    titleEn: "Unfair Dismissal",
    descriptionAr: "حقوق العامل في حالة الفصل التعسفي والتعويضات المستحقة",
    descriptionEn: "Worker rights in cases of unfair dismissal and entitled compensation",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "wage-limitation",
    slug: "wage-limitation",
    filename: "jordan-wage-limitation-infographic-branded.png",
    category: "Labor Law",
    titleAr: "تقادم الأجور",
    titleEn: "Wage Limitation",
    descriptionAr: "فترة التقادم القانوني للمطالبة بالأجور المستحقة في العمل",
    descriptionEn: "Statutory limitation period for claiming unpaid wages in employment",
    language: "ar",
    template: "deadline-warning",
    lastReviewed: "2026-08-18",
  },

  // ── Traffic Law ────────────────────────────────────────────
  {
    id: "accident-roadmap",
    slug: "traffic-accident-liability",
    filename: "jordan-traffic-accident-roadmap-infographic-branded.png",
    category: "Traffic Law",
    titleAr: "خارطة طريق حوادث المرور",
    titleEn: "Traffic Accident Roadmap",
    descriptionAr: "خارطة طريق شاملة للخطوات الواجب اتخاذها بعد حادث المرور",
    descriptionEn: "Comprehensive roadmap of steps to take after a traffic accident",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "fault-damage-assessment",
    slug: "traffic-fault-damage",
    filename: "jordan-traffic-fault-damage-assessment-infographic-branded.png",
    category: "Traffic Law",
    titleAr: "تقييم الخطأ والضرر",
    titleEn: "Fault and Damage Assessment",
    descriptionAr: "كيفية تقييم نسبة الخطأ والضرر في حوادث المرور قانونياً",
    descriptionEn: "How to legally assess the degree of fault and damage in traffic accidents",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "report-objection",
    slug: "traffic-report-objection",
    filename: "traffic-accident-report-objection-infographic-final.png",
    category: "Traffic Law",
    titleAr: "اعتراض تقرير الحادث",
    titleEn: "Traffic Report Objection",
    descriptionAr: "إجراءات الطعن على تقرير الشرطة الخاص بحوادث المرور",
    descriptionEn: "Procedures for objecting to the police report on traffic accidents",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "report-administrative-vs-judicial",
    slug: "traffic-report-types",
    filename: "traffic-report-administrative-vs-judicial-infographic-final.png",
    category: "Traffic Law",
    titleAr: "التقرير الإداري مقابل القضائي",
    titleEn: "Administrative vs Judicial Report",
    descriptionAr: "الفرق بين التقرير الإداري والتقرير القضائي في حوادث المرور",
    descriptionEn: "Difference between administrative and judicial reports in traffic accidents",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },

  // ── Civil Law ──────────────────────────────────────────────
  {
    id: "civil-code-admission-ar",
    slug: "civil-code-admission",
    filename: "jordan-civil-code-admission-infographic-ar.png",
    category: "Civil Law",
    titleAr: "الإقرار في القانون المدني",
    titleEn: "Civil Code Admission",
    descriptionAr: "أحكام الإقرار وإثباته في القانون المدني الأردني",
    descriptionEn: "Rules on admission and proof under the Jordanian Civil Code",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "civil-law-rights",
    slug: "civil-law-rights",
    filename: "jordan-civil-law-rights-infographic.png",
    category: "Civil Law",
    titleAr: "حقوق القانون المدني",
    titleEn: "Civil Law Rights",
    descriptionAr: "نظرة عامة على الحقوق المدنية المكفولة للأشخاص في الأردن",
    descriptionEn: "Overview of civil rights guaranteed to individuals in Jordan",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "legal-foundations",
    slug: "civil-code-foundations",
    filename: "Jordanian_Civil_Code_Legal_Foundations.png",
    category: "Civil Law",
    titleAr: "الأساس القانوني للقانون المدني",
    titleEn: "Civil Code Legal Foundations",
    descriptionAr: "المبادئ والأساس القانونية التي يقوم عليها القانون المدني الأردني",
    descriptionEn: "Legal principles and foundations underlying the Jordanian Civil Code",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "real-rights-ar",
    slug: "real-rights",
    filename: "jordan-real-rights-infographic-ar.png",
    category: "Civil Law",
    titleAr: "الحقوق العينية",
    titleEn: "Real Rights",
    descriptionAr: "أنواع الحقوق العينية في القانون المدني واستعمالاتها",
    descriptionEn: "Types of real rights under civil law and their applications",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "pledge",
    slug: "pledge",
    filename: "jordan-pledge-infographic.png",
    category: "Civil Law",
    titleAr: "الرهن",
    titleEn: "Pledge",
    descriptionAr: "أحكام الرهن في القانون المدني وحقوق الدائن والمدين",
    descriptionEn: "Pledge rules under civil law and rights of creditor and debtor",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "mortgage-types-ar",
    slug: "mortgage-types",
    filename: "jordan-mortgage-types-infographic-ar.png",
    category: "Civil Law",
    titleAr: "أنواع الرهن العقاري",
    titleEn: "Mortgage Types",
    descriptionAr: "مقارنة بين أنواع الرهن العقاري المتاحة في القانون الأردني",
    descriptionEn: "Comparison of mortgage types available under Jordanian law",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "civil-code-rights-ar",
    slug: "civil-code-rights",
    filename: "حقوقك_في_القانون_المدني_الأردني.png",
    category: "Civil Law",
    titleAr: "حقوقك في القانون المدني الأردني",
    titleEn: "Your Rights in Jordanian Civil Code",
    descriptionAr: "دليل مبسط لحقوقك المدنية وفقاً للقانون المدني الأردني",
    descriptionEn: "Simplified guide to your civil rights under the Jordanian Civil Code",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },

  // ── Legal Services ─────────────────────────────────────────
  {
    id: "electronic-notices",
    slug: "electronic-notices",
    filename: "jordan-electronic-notices-infographic-branded.png",
    category: "Legal Services",
    titleAr: "الإشعارات الإلكترونية",
    titleEn: "Electronic Notices",
    descriptionAr: "شرعية الإشعارات الإلكترونية وقيمتها القانونية في الأردن",
    descriptionEn: "Legality of electronic notices and their legal validity in Jordan",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "email-legal-service",
    slug: "email-legal-service",
    filename: "jordan-email-legal-service-infographic-branded.png",
    category: "Legal Services",
    titleAr: "الخدمة القانونية عبر البريد الإلكتروني",
    titleEn: "Email Legal Service",
    descriptionAr: "هل تُقبل الخدمة القانونية عبر البريد الإلكتروني في المحاكم الأردنية",
    descriptionEn: "Whether email legal service is accepted in Jordanian courts",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "email-service-conditions",
    slug: "email-service-conditions",
    filename: "jordan-email-service-conditions-infographic-branded.png",
    category: "Legal Services",
    titleAr: "شروط الخدمة عبر البريد الإلكتروني",
    titleEn: "Email Service Conditions",
    descriptionAr: "الشروط والمتطلبات القانونية لخدمة الإشعارات عبر البريد الإلكتروني",
    descriptionEn: "Legal conditions and requirements for serving notices via email",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "foreign-marriage",
    slug: "foreign-marriage",
    filename: "jordan-foreign-marriage-requirements-infographic-branded.png",
    category: "Legal Services",
    titleAr: "متطلبات الزواج الأجنبي",
    titleEn: "Foreign Marriage Requirements",
    descriptionAr: "المستندات والمتطلبات القانونية لتسجيل الزواج الأجنبي في الأردن",
    descriptionEn: "Documents and legal requirements for registering foreign marriages in Jordan",
    language: "both",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "legal-content-topics",
    slug: "legal-content-topics",
    filename: "jordan-legal-content-topics-infographic-branded.png",
    category: "Legal Services",
    titleAr: "مواضيع المحتوى القانوني",
    titleEn: "Legal Content Topics",
    descriptionAr: "نظرة عامة على مواضيع المحتوى القانوني المتاحة في المنصة",
    descriptionEn: "Overview of legal content topics available on the platform",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "whatsapp-legal-service",
    slug: "whatsapp-legal-service",
    filename: "jordan-whatsapp-legal-service-infographic-branded.png",
    category: "Legal Services",
    titleAr: "الخدمة القانونية عبر واتساب",
    titleEn: "WhatsApp Legal Service",
    descriptionAr: "كيفية استخدام واتساب للحصول على خدمات قانونية واستشارات",
    descriptionEn: "How to use WhatsApp for legal services and consultations",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "responsible-ai-ar",
    slug: "responsible-ai",
    filename: "responsible_ai_legal_work_jordan_ar.png",
    category: "Legal Services",
    titleAr: "الذكاء الاصطناعي المسؤول في العمل القانوني",
    titleEn: "Responsible AI in Legal Work",
    descriptionAr: "مبادئ استخدام الذكاء الاصطناعي المسؤول في الخدمات القانونية",
    descriptionEn: "Principles of responsible AI use in legal services",
    language: "ar",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "expat-services",
    slug: "expat-services",
    filename: "خدمات_المغتربين_القانونية__1_-removebg-preview.png",
    category: "Legal Services",
    titleAr: "خدمات المغتربين القانونية",
    titleEn: "Legal Services for Expats",
    descriptionAr: "الخدمات القانونية المتاحة للمغتربين والعاملين في الأردن",
    descriptionEn: "Legal services available to expatriates and foreign workers in Jordan",
    language: "both",
    template: "legal-summary",
    lastReviewed: "2026-08-18",
  },
  {
    id: "legal-transactions-steps",
    slug: "legal-transactions",
    filename: "خطوات_إنجاز_المعاملات_القانونية_بالأردن.png",
    category: "Legal Services",
    titleAr: "خطوات إنجاز المعاملات القانونية",
    titleEn: "Legal Transaction Steps",
    descriptionAr: "الخطوات العملية لإتمام المعاملات القانونية المختلفة في الأردن",
    descriptionEn: "Practical steps for completing various legal transactions in Jordan",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
  {
    id: "oral-contracts-guide",
    slug: "oral-contracts",
    filename: "إرادتك_ملزمة__دليل_العقود_الشفهية.png",
    category: "Legal Services",
    titleAr: "دليل العقود الشفهية",
    titleEn: "Oral Contracts Guide",
    descriptionAr: "القيمة القانونية للعقود الشفهية وإثباتها أمام المحاكم الأردنية",
    descriptionEn: "Legal value of oral contracts and proving them in Jordanian courts",
    language: "ar",
    template: "procedural-guide",
    lastReviewed: "2026-08-18",
  },
];
