import type { Lawyer, PracticeArea } from "./types";

const lawyers: Lawyer[] = [
  {
    id: "lawyer-001",
    name_ar: "أحمد فهد الخطيب",
    name_en: "Ahmad Fahd Al-Khatib",
    membership_id: "JBA-1023",
    practice_areas: ["labor", "debt"],
    governorates: ["Amman"],
    languages: ["Arabic", "English"],
    service_types: ["consultation", "litigation", "drafting"],
    pricing: "50 JOD/hour",
    verification_status: "verified",
    verification_date: "2024-01-15",
    bio_ar: "محامٍ متخصص في قانون العمل والديون، خريج الجامعة الأردنية. يمتلك خبرة تمتد لأكثر من 15 عاماً في التعامل مع قضايا فصل موظفين غير قانوني وتحصيل الديون. عمل سابقاً في مكتب المحامي عبد الكريم الخطيب و Associates.",
    bio_en: "A labor and debt law specialist, graduate of the University of Jordan. With over 15 years of experience handling wrongful termination and debt collection cases. Previously worked at Al-Khatib & Associates law firm.",
    phone: "+962-79-123-4567",
    email: "ahmad.khatib@example.jo",
    years_experience: 15,
    rating: 4.8,
  },
  {
    id: "lawyer-002",
    name_ar: "نورهان سامي العموسي",
    name_en: "Norhan Sami Al-Omousi",
    membership_id: "JBA-2047",
    practice_areas: ["family", "rent"],
    governorates: ["Amman", "Salt"],
    languages: ["Arabic", "English", "French"],
    service_types: ["consultation", "litigation", "enforcement"],
    pricing: "60 JOD/hour",
    verification_status: "verified",
    verification_date: "2023-11-20",
    bio_ar: "محامية متخصصة في الأحوال الشخصية وقانون الإيجارات. حاصلة على ماجستير في القانون من الجامعة الأردنية. تتحدث العربية والإنجليزية والفرنسية بطلاق. لها خبرة واسعة في قضايا الطلاق والممتلكات.",
    bio_en: "A family and rent law specialist with a Master's degree in Law from the University of Jordan. Fluent in Arabic, English, and French. Extensive experience in divorce and property cases.",
    phone: "+962-79-234-5678",
    email: "norhan.omousi@example.jo",
    years_experience: 12,
    rating: 4.7,
  },
  {
    id: "lawyer-003",
    name_ar: "خالد يوسف الصرايره",
    name_en: "Khaled Yousef Al-Sarayrah",
    membership_id: "JBA-3156",
    practice_areas: ["traffic", "cybercrime"],
    governorates: ["Irbid"],
    languages: ["Arabic", "English"],
    service_types: ["consultation", "litigation"],
    pricing: "40 JOD/hour",
    verification_status: "verified",
    verification_date: "2024-03-10",
    bio_ar: "محامٍ متخصص في قانون المرور والجرائم الإلكترونية. يخدم منطقة إربد والمحافظات الشمالية. حاصل على بكالوريوس الحقوق من جامعة اليرموك. تميز في التعامل مع قضايا المخالفات المرورية والاحتيال الإلكتروني.",
    bio_en: "A traffic and cybercrime law specialist serving Irbid and northern governorates. Holds a Bachelor of Law from Yarmouk University. Expertise in traffic violation and online fraud cases.",
    phone: "+962-79-345-6789",
    email: "khaled.sarayrah@example.jo",
    years_experience: 8,
    rating: 4.5,
  },
  {
    id: "lawyer-004",
    name_ar: "ريم عادل القضاة",
    name_en: "Rima Adel Al-Qudah",
    membership_id: "JBA-4289",
    practice_areas: ["family", "debt", "small_business"],
    governorates: ["Amman"],
    languages: ["Arabic", "English"],
    service_types: ["consultation", "litigation", "enforcement", "drafting"],
    pricing: "75 JOD/hour",
    verification_status: "verified",
    verification_date: "2023-08-05",
    bio_ar: "محامية ومستشارة قانونية متعددة التخصصات. حاصلة على دكتوراه في القانون من الجامعة الأردنية. تقدم خدمات استشارية وتمثيل قضائي في قضايا الأحوال الشخصية والديون وتأسيس الشركات الصغيرة. من أبرز المحامين في عمان.",
    bio_en: "A multidisciplinary lawyer and legal consultant. Holds a PhD in Law from the University of Jordan. Provides legal consultation and litigation in family law, debt, and small business formation. One of the top lawyers in Amman.",
    phone: "+962-79-456-7890",
    email: "rima.qudah@example.jo",
    years_experience: 20,
    rating: 4.9,
  },
  {
    id: "lawyer-005",
    name_ar: "عمر مصطفى الزعبي",
    name_en: "Omar Mustafa Al-Zoubi",
    membership_id: "JBA-5512",
    practice_areas: ["rent", "small_business"],
    governorates: ["Zarqa"],
    languages: ["Arabic"],
    service_types: ["consultation", "drafting"],
    pricing: "35 JOD/hour",
    verification_status: "verified",
    verification_date: "2024-05-22",
    bio_ar: "محامٍ متخصص في قوانين الإيجارات وتأسيس الشركات الصغيرة في محافظة الزرقاء. يتمتع بخبرة تزيد عن 10 سنوات في مراجعة عقود الإيجار وتصديق العقود. يقدم خدمات بأسعار معقولة للسكان والشركات الصغيرة.",
    bio_en: "A rent and small business law specialist in Zarqa governorate. Over 10 years of experience in lease contract review and contract notarization. Offers affordable services for residents and small businesses.",
    phone: "+962-79-567-8901",
    email: "omar.zoubi@example.jo",
    years_experience: 10,
    rating: 4.4,
  },
  {
    id: "lawyer-006",
    name_ar: "سلمى حسينين العتيبي",
    name_en: "Salma Hussienen Al-Otaibi",
    membership_id: "JBA-6678",
    practice_areas: ["labor", "family"],
    governorates: ["Aqaba"],
    languages: ["Arabic", "English"],
    service_types: ["consultation", "litigation", "enforcement"],
    pricing: "45 JOD/hour",
    verification_status: "verified",
    verification_date: "2024-02-28",
    bio_ar: "محامية متخصصة في قانون العمل والأحوال الشخصية في مدينة العقبة. حاصلة على بكالوريوس الحقوق من جامعة الحسين بن طلال. خبرة في قضايا التوظيف التعسفي والأحوال الشخصية في المناطق الحدودية والبحرية.",
    bio_en: "A labor and family law specialist in Aqaba city. Holds a Bachelor of Law from Al-Hussein Bin Talal University. Experienced in unfair employment practices and family matters in border and coastal regions.",
    phone: "+962-79-678-9012",
    email: "salma.otaibi@example.jo",
    years_experience: 6,
    rating: 4.3,
  },
  {
    id: "lawyer-007",
    name_ar: "محمد إبراهيم الخلايلة",
    name_en: "Mohammed Ibrahim Al-Khalayleh",
    membership_id: "JBA-7734",
    practice_areas: ["debt", "court_procedures"],
    governorates: ["Karak"],
    languages: ["Arabic"],
    service_types: ["litigation", "enforcement"],
    pricing: "30 JOD/hour",
    verification_status: "verified",
    verification_date: "2023-12-01",
    bio_ar: "محامٍ متخصص في المحاكم والإجراءات القضائية وتحصيل الديون في محافظة الكرك. يمتلك خبرة واسعة في التعامل مع المحاكم المحلية. يخدم سكان المحافظات الجنوبية بخبرة تمتد لأكثر من 18 عاماً.",
    bio_en: "A court procedures and debt collection specialist in Karak governorate. Extensive experience dealing with local courts. Serves residents of southern governorates with over 18 years of experience.",
    phone: "+962-79-789-0123",
    email: "mohammed.khalayleh@example.jo",
    years_experience: 18,
    rating: 4.6,
  },
  {
    id: "lawyer-008",
    name_ar: "هدى فؤاد الكردي",
    name_en: "Huda Fouad Al-Kurdi",
    membership_id: "JBA-8845",
    practice_areas: ["cybercrime", "small_business"],
    governorates: ["Amman", "Zarqa"],
    languages: ["Arabic", "English"],
    service_types: ["consultation", "litigation", "drafting"],
    pricing: "55 JOD/hour",
    verification_status: "verified",
    verification_date: "2024-04-15",
    bio_ar: "محامية متخصصة في الجرائم الإلكترونية وتأسيس الشركات. حاصلة على ماجستير في القانون الرقمي من معهد الحقوق الأردني. متخصصة في حماية البيانات وقوانين التجارة الإلكترونية وتأسيس الشركات التقنية.",
    bio_en: "A cybercrime and business formation specialist. Holds a Master's in Digital Law from the Jordanian Institute of Law. Specializes in data protection, e-commerce law, and tech company formation.",
    phone: "+962-79-890-1234",
    email: "huda.kurdi@example.jo",
    years_experience: 7,
    rating: 4.5,
  },
  {
    id: "lawyer-009",
    name_ar: "طارق جمال الحصني",
    name_en: "Tariq Jamal Al-Hasanat",
    membership_id: "JBA-9901",
    practice_areas: ["rent", "court_procedures", "labor"],
    governorates: ["Salt"],
    languages: ["Arabic", "English"],
    service_types: ["consultation", "litigation", "enforcement", "drafting"],
    pricing: "42 JOD/hour",
    verification_status: "verified",
    verification_date: "2024-01-30",
    bio_ar: "محامٍ متعدد التخصصات في مدينة السلط. متخصص في قوانين الإيجارات والإجراءات القضائية وقانون العمل. حاصل على بكالوريوس الحقوق من جامعة آل البيت. يقدم خدمات شاملة للسكان والشركات في محافظة البلقاء.",
    bio_en: "A multi-practice lawyer in Salt city. Specializes in rent law, court procedures, and labor law. Holds a Bachelor of Law from Al al-Bayt University. Provides comprehensive services for residents and businesses in Balqa governorate.",
    phone: "+962-79-901-2345",
    email: "tariq.hasanat@example.jo",
    years_experience: 14,
    rating: 4.7,
  },
  {
    id: "lawyer-010",
    name_ar: "إيمان خالد البشايرة",
    name_en: "Iman Khaled Al-Bashaireh",
    membership_id: "JBA-1108",
    practice_areas: ["family", "debt"],
    governorates: ["Madaba"],
    languages: ["Arabic", "English", "French"],
    service_types: ["consultation", "litigation"],
    pricing: "48 JOD/hour",
    verification_status: "verified",
    verification_date: "2023-10-18",
    bio_ar: "محامية متخصصة في الأحوال الشخصية والديون في محافظة مادبا. تتحدث العربية والإنجليزية والفرنسية. حاصلة على ماجستير في القانون من جامعة باريس. لها خبرة واسعة في قضايا الأحوال الشخصية الدولية وتحصيل الديون.",
    bio_en: "A family and debt law specialist in Madaba governorate. Fluent in Arabic, English, and French. Holds a Master's in Law from the University of Paris. Extensive experience in international family law and debt collection.",
    phone: "+962-77-123-4567",
    email: "iman.bashaireh@example.jo",
    years_experience: 9,
    rating: 4.6,
  },
  {
    id: "lawyer-011",
    name_ar: "ياسين ناصر المحارمه",
    name_en: "Yaseen Nasser Al-Mohareme",
    membership_id: "JBA-2219",
    practice_areas: ["traffic", "labor"],
    governorates: ["Irbid", "Ramtha"],
    languages: ["Arabic"],
    service_types: ["consultation", "litigation", "enforcement"],
    pricing: "38 JOD/hour",
    verification_status: "verified",
    verification_date: "2024-06-10",
    bio_ar: "محامٍ متخصص في قانون المرور وقانون العمل في إربد والرمثا. حاصل على بكالوريوس الحقوق من جامعة اليرموك. يتمتع بخبرة تمتد لأكثر من 5 سنوات في التعامل مع المخالفات المرورية وقضايا التوظيف في الشمال.",
    bio_en: "A traffic and labor law specialist in Irbid and Ramtha. Holds a Bachelor of Law from Yarmouk University. Over 5 years of experience handling traffic violations and employment cases in the north.",
    phone: "+962-77-234-5678",
    email: "yaseen.mohareme@example.jo",
    years_experience: 5,
    rating: 4.2,
  },
  {
    id: "lawyer-012",
    name_ar: "ديمة حسن الصברי",
    name_en: "Dima Hassan Al-Subari",
    membership_id: "JBA-3327",
    practice_areas: ["small_business", "cybercrime"],
    governorates: ["Amman"],
    languages: ["Arabic", "English"],
    service_types: ["consultation", "drafting"],
    pricing: "65 JOD/hour",
    verification_status: "verified",
    verification_date: "2024-02-05",
    bio_ar: "محامية متخصصة في الشركات الصغيرة والجرائم الإلكترونية. حاصلة على ماجستير في القانون التجاري من الجامعة الأردنية. متخصصة في تأسيس الشركات الناشئة وحماية الملكية الفكرية وقوانين الوسائط الرقمية.",
    bio_en: "A small business and cybercrime law specialist. Holds a Master's in Commercial Law from the University of Jordan. Specializes in startup formation, intellectual property protection, and digital media law.",
    phone: "+962-77-345-6789",
    email: "dima.subari@example.jo",
    years_experience: 11,
    rating: 4.8,
  },
  {
    id: "lawyer-013",
    name_ar: "عبدالرحمن منصور القحطاني",
    name_en: "Abdulrahman Mansour Al-Qahtani",
    membership_id: "JBA-4438",
    practice_areas: ["court_procedures", "debt", "rent"],
    governorates: ["Zarqa", "Amman"],
    languages: ["Arabic", "English"],
    service_types: ["litigation", "enforcement"],
    pricing: "44 JOD/hour",
    verification_status: "verified",
    verification_date: "2023-09-25",
    bio_ar: "محامٍ متخصص في الإجراءات القضائية وتحصيل الديون وقوانين الإيجار في الزرقاء وعمان. حاصل على بكالوريوس الحقوق من جامعة الزرقاء الأهلية. خبرة في التمثيل أمام المحاكم المحلية والمركزية لأكثر من 13 عاماً.",
    bio_en: "A court procedures, debt collection, and rent law specialist in Zarqa and Amman. Holds a Bachelor of Law from Zarqa Private University. Experience representing clients in local and central courts.",
    phone: "+962-77-456-7890",
    email: "abdulrahman.qahtani@example.jo",
    years_experience: 13,
    rating: 4.5,
  },
  {
    id: "lawyer-014",
    name_ar: "سارة أحمد المعايطة",
    name_en: "Sara Ahmad Al-Ma'aytah",
    membership_id: "JBA-5549",
    practice_areas: ["family", "labor"],
    governorates: ["Karak", "Tafilah"],
    languages: ["Arabic", "English"],
    service_types: ["consultation", "litigation", "drafting"],
    pricing: "36 JOD/hour",
    verification_status: "verified",
    verification_date: "2024-07-12",
    bio_ar: "محامية متخصصة في الأحوال الشخصية وقانون العمل في محافظة الكرك والطفيلة. حاصلة على بكالوريوس الحقوق من جامعة الحسين بن طلال. متخصصة في قضايا حضانة الأطفال وقانون العمل في المناطق الريفية.",
    bio_en: "A family and labor law specialist in Karak and Tafilah governorates. Holds a Bachelor of Law from Al-Hussein Bin Talal University. Specializes in child custody cases and rural employment law.",
    phone: "+962-77-567-8901",
    email: "sara.maaytah@example.jo",
    years_experience: 4,
    rating: 4.3,
  },
  {
    id: "lawyer-015",
    name_ar: "فهد عبدالعزيز الدهيش",
    name_en: "Fahd Abdulaziz Al-Dahayes",
    membership_id: "JBA-6660",
    practice_areas: ["debt", "small_business", "court_procedures"],
    governorates: ["Aqaba", "Amman"],
    languages: ["Arabic", "English"],
    service_types: ["consultation", "litigation", "enforcement", "drafting"],
    pricing: "70 JOD/hour",
    verification_status: "verified",
    verification_date: "2023-07-08",
    bio_ar: "محامٍ ومستشار قانوني بخبرة تمتد لأكثر من 25 عاماً. متخصص في الديون والشركات الصغيرة والإجراءات القضائية. حاصل على ماجستير في القانون التجاري من جامعة عمان العربية. من أقدم المحامين في العقبة وعمان.",
    bio_en: "A lawyer and legal consultant with over 25 years of experience. Specializes in debt, small business, and court procedures. Holds a Master's in Commercial Law from Amman Arab University. One of the most experienced lawyers in Aqaba and Amman.",
    phone: "+962-77-678-9012",
    email: "fahd.dahayes@example.jo",
    years_experience: 25,
    rating: 4.9,
  },
];

export function getLawyers(): Lawyer[] {
  return lawyers;
}

export function getLawyerById(id: string): Lawyer | undefined {
  return lawyers.find((l) => l.id === id);
}

export function getLawyersByArea(area: PracticeArea): Lawyer[] {
  return lawyers.filter((l) => l.practice_areas.includes(area));
}

export function getLawyersByGovernorate(governorate: string): Lawyer[] {
  return lawyers.filter((l) =>
    l.governorates.some((g) => g.toLowerCase() === governorate.toLowerCase())
  );
}

export default lawyers;
